name = "uithub_pipe"
main = "urlPipe.ts"
compatibility_date = "2025-04-01"
dev.port = 3000
routes = [
  { pattern = "pipe.uithub.com", custom_domain = true }
]
limits.cpu_ms = 300000

# [[services]]
# binding = "OUTPUTZIP_UITHUB_COM_FETCHER"
# service = "uithub_outputzip"

# [[services]]
# binding = "SEARCH_UITHUB_COM_FETCHER"
# service = "uithub_search"

# [[services]]
# binding = "INGESTZIP_UITHUB_COM_FETCHER"
# service = "uithub_ingestzip"