name = "uithub_ziptree"
main = "main.js"
compatibility_date = "2025-03-01"
dev.port = 3000

assets.directory = "./public"

route.pattern = "ziptree.uithub.com"
route.custom_domain = true

[[kv_namespaces]]
binding = "ZIPTREE_KV"
id = "0cc18c0c12604358814ca4592ff02578"